export { default as Info } from './info.vue'
export { default as About } from './about.vue'
export { default as Skills } from './skills.vue'
export { default as Experience } from './experience.vue'
export { default as Education } from './education.vue'
export { default as CodeExample } from './examples/code.vue'
export { default as Examples } from './examples/examples.vue'
